import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/providers/storeProvider";
import AuthProvider from "@/providers/authProvider";
import ThemeProvider from "@/providers/themeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <AuthProvider>
        <ThemeProvider>{children}</ThemeProvider>
      </AuthProvider>
    </StoreProvider>
  );
}
